In [1]:
import pandas as pd
import numpy as np

#Dataset 1:
-----------

##1.Load Dataset

In [3]:
df = pd.read_csv("AB_NYC_2019.csv")

##View Dataset

In [25]:
df.head()

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40840 entries, 0 to 40839
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40840 non-null  object
 1   trending_date           40840 non-null  object
 2   title                   40840 non-null  object
 3   channel_title           40840 non-null  object
 4   category_id             40840 non-null  int64
 5   publish_time            40840 non-null  object
 6   tags                    40840 non-null  object
 7   views                   40840 non-null  int64
 8   likes                   40840 non-null  int64
 9   dislikes                40840 non-null  int64
 10  comment_count           40840 non-null  int64
 11  thumbnail_link          40840 non-null  object
 12  comments_disabled       40840 non-null  bool
 13  ratings_disabled        40840 non-null  bool
 14  video_error_or_removed  40840 non-null  bool
 15  description             39288 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.2+ MB

        category_id         views         likes      dislikes  comment_count
count  40840.000000  4.084000e+04  4.084000e+04  4.084000e+04   4.084000e+04
mean      20.705828  6.034553e+05  2.187550e+04  1.397136e+03   2.785857e+03
std        6.975813  2.348963e+06  1.018000e+05  1.457738e+04   1.745803e+04
min        1.000000  5.180000e+02  0.000000e+00  0.000000e+00   0.000000e+00
25%       20.000000  2.706875e+04  5.330000e+02  2.900000e+01   7.900000e+01
50%       24.000000  1.192770e+05  2.699000e+03  1.340000e+02   3.760000e+02
75%       24.000000  4.431015e+05  1.179625e+04  5.320000e+02   1.376000e+03
max       44.000000  1.138762e+08  4.924056e+06  1.470386e+06   1.084435e+06

##2.Check Missing Values

In [23]:
df.isnull().sum()

video_id                     0
trending_date                0
title                        0
channel_title                0
category_id                  0
publish_time                 0
tags                         0
views                        0
likes                        0
dislikes                     0
comment_count                0
thumbnail_link               0
comments_disabled            0
ratings_disabled             0
video_error_or_removed       0
description               1552
dtype: int64

##Handle Missing Values

Fill numerical missing values with mean

In [11]:
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipykernel_5316/4057150236.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mean(), inplace=True)

Fill categorical missing values with mode

In [12]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_5316/2422164989.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

##3.Check Duplicate Records

In [55]:
df.duplicated().sum()

np.int64(0)

##Remove Duplicates

In [56]:
df.drop_duplicates(inplace=True)

#4.Standardization

Convert text to lowercase

In [15]:
for col in cat_cols:
    df[col] = df[col].str.lower()

Remove extra spaces

In [16]:
for col in cat_cols:
    df[col] = df[col].str.strip()

#5.Outlier Detection

Detect Outliers Using IQR Method

In [17]:
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(col, "Outliers:", len(outliers))

id Outliers: 0
host_id Outliers: 1526
latitude Outliers: 425
longitude Outliers: 2833
price Outliers: 2972
minimum_nights Outliers: 6607
number_of_reviews Outliers: 6021
reviews_per_month Outliers: 4103
calculated_host_listings_count Outliers: 7081
availability_365 Outliers: 0

Remove Outliers

In [19]:
for col in num_cols:

    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

#Final Clean Dataset

In [20]:
print(df.info())

print(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 12313 entries, 26 to 48872
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              12313 non-null  int64
 1   name                            12313 non-null  object
 2   host_id                         12313 non-null  int64
 3   host_name                       12313 non-null  object
 4   neighbourhood_group             12313 non-null  object
 5   neighbourhood                   12313 non-null  object
 6   latitude                        12313 non-null  float64
 7   longitude                       12313 non-null  float64
 8   room_type                       12313 non-null  object
 9   price                           12313 non-null  int64
 10  minimum_nights                  12313 non-null  int64
 11  number_of_reviews               12313 non-null  int64
 12  last_review                     12313 non-null  object
 13  reviews_per_month               12313 non-null  float64
 14  calculated_host_listings_count  12313 non-null  int64
 15  availability_365                12313 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 1.6+ MB
None
        id                                               name  host_id  \
26    8700  magnifique suite au n de manhattan - vue cloitres    26394
48   13050                          bright and stylish duplex    50846
66   16458  light-filled 2b duplex in the heart of park sl...    64056
88   20300                             great location for nyc    76627
123  27883                             east village sanctuary   120223

           host_name neighbourhood_group       neighbourhood  latitude  \
26   claude & sophie           manhattan              inwood  40.86754
48          jennifer            brooklyn  bedford-stuyvesant  40.68554
66              sara            brooklyn          park slope  40.67343
88               pas           manhattan        east village  40.72912
123              jen           manhattan        east village  40.72245

     longitude        room_type  price  minimum_nights  number_of_reviews  \
26   -73.92639     private room     80               4                  0
48   -73.94090  entire home/apt    115               3                 11
66   -73.98338  entire home/apt    225               3                  4
88   -73.98057     private room     50               1                  2
123  -73.98527  entire home/apt    100               4                 25

    last_review  reviews_per_month  calculated_host_listings_count  \
26   2019-06-23           1.373221                               1
48   2017-01-01           0.100000                               1
66   2017-09-24           0.160000                               1
88   2016-02-14           0.050000                               1
123  2011-12-10           0.230000                               1

     availability_365
26                  0
48                  0
66                  0
88                  0
123                 0

#Dataset 2:
-----------

##1.Load Dataset

In [43]:
df2=pd.read_csv("CAvideos.csv")
df2=pd.read_csv("DEvideos.csv")

##View Dataset

In [44]:
df2.head()

df2.info()

df2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40840 entries, 0 to 40839
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40840 non-null  object
 1   trending_date           40840 non-null  object
 2   title                   40840 non-null  object
 3   channel_title           40840 non-null  object
 4   category_id             40840 non-null  int64
 5   publish_time            40840 non-null  object
 6   tags                    40840 non-null  object
 7   views                   40840 non-null  int64
 8   likes                   40840 non-null  int64
 9   dislikes                40840 non-null  int64
 10  comment_count           40840 non-null  int64
 11  thumbnail_link          40840 non-null  object
 12  comments_disabled       40840 non-null  bool
 13  ratings_disabled        40840 non-null  bool
 14  video_error_or_removed  40840 non-null  bool
 15  description             39288 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.2+ MB

        category_id         views         likes      dislikes  comment_count
count  40840.000000  4.084000e+04  4.084000e+04  4.084000e+04   4.084000e+04
mean      20.705828  6.034553e+05  2.187550e+04  1.397136e+03   2.785857e+03
std        6.975813  2.348963e+06  1.018000e+05  1.457738e+04   1.745803e+04
min        1.000000  5.180000e+02  0.000000e+00  0.000000e+00   0.000000e+00
25%       20.000000  2.706875e+04  5.330000e+02  2.900000e+01   7.900000e+01
50%       24.000000  1.192770e+05  2.699000e+03  1.340000e+02   3.760000e+02
75%       24.000000  4.431015e+05  1.179625e+04  5.320000e+02   1.376000e+03
max       44.000000  1.138762e+08  4.924056e+06  1.470386e+06   1.084435e+06

#2.Check Missing Values

In [45]:
df2.isnull().sum()

video_id                     0
trending_date                0
title                        0
channel_title                0
category_id                  0
publish_time                 0
tags                         0
views                        0
likes                        0
dislikes                     0
comment_count                0
thumbnail_link               0
comments_disabled            0
ratings_disabled             0
video_error_or_removed       0
description               1552
dtype: int64

#Handle Missing Values

Numerical Columns

In [46]:
num_cols = df2.select_dtypes(include=np.number).columns

for col in num_cols:
    df2[col].fillna(df2[col].mean(), inplace=True)

/tmp/ipykernel_5316/1000411754.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2[col].fillna(df2[col].mean(), inplace=True)

Categorical Columns

In [47]:
cat_cols = df2.select_dtypes(include='object').columns

for col in cat_cols:
    df2[col].fillna(df2[col].mode()[0], inplace=True)

/tmp/ipykernel_5316/1189126208.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2[col].fillna(df2[col].mode()[0], inplace=True)

#3.Check Duplicate Records

In [48]:
df2.duplicated().sum()

np.int64(0)

##Remove Duplicates

In [49]:
df2.drop_duplicates(inplace=True)

#4.Standardization

Convert text to lowercase

In [51]:
for col in cat_cols:
    df2[col] = df2[col].str.lower()

Remove extra spaces

In [50]:
for col in cat_cols:
    df2[col] = df2[col].str.strip()

#5.Outlier Detection

Detect Outliers Using IQR Method

In [52]:
for col in num_cols:

    Q1 = df2[col].quantile(0.25)
    Q3 = df2[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df2[(df2[col] < lower) | (df2[col] > upper)]

    print(col, "Outliers:", len(outliers))

category_id Outliers: 5729
views Outliers: 4742
likes Outliers: 5263
dislikes Outliers: 5574
comment_count Outliers: 5488

Remove Outliers

In [53]:
for col in num_cols:

    Q1 = df2[col].quantile(0.25)
    Q3 = df2[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df2 = df2[(df2[col] >= lower) & (df2[col] <= upper)]

#Final Clean Dataset

In [54]:
print(df2.info())

print(df2.head())

<class 'pandas.core.frame.DataFrame'>
Index: 22961 entries, 5 to 40839
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                22961 non-null  object
 1   trending_date           22961 non-null  object
 2   title                   22961 non-null  object
 3   channel_title           22961 non-null  object
 4   category_id             22961 non-null  int64
 5   publish_time            22961 non-null  object
 6   tags                    22961 non-null  object
 7   views                   22961 non-null  int64
 8   likes                   22961 non-null  int64
 9   dislikes                22961 non-null  int64
 10  comment_count           22961 non-null  int64
 11  thumbnail_link          22961 non-null  object
 12  comments_disabled       22961 non-null  bool
 13  ratings_disabled        22961 non-null  bool
 14  video_error_or_removed  22961 non-null  bool
 15  description             22961 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 2.5+ MB
None
       video_id trending_date  \
5   xapgfgwqtg4      17.14.11
13  mmmpprcmjea      17.14.11
14  3u51cviqulm      17.14.11
15  okyuthvgmhc      17.14.11
16  spwqqdcw4ti      17.14.11

                                                title  \
5   geld verdienen mit online-umfragen? geht das w...
13  diese schlafposition solltest du unbedingt ver...
14                    arab lifestyle | mit bodyformus
15      die welt in 30 jahren - sommer 2047 -  volkan
16         rundlauf fußball challenge + bestrafung !!

                                   channel_title  category_id  \
5                                die allestester           22
13  liebscher & bracht | die schmerzspezialisten           17
14                                   planetkanax           23
15                                        volkan           24
16                                      brotatos           24

                publish_time  \
5   2017-11-13t01:49:24.000z
13  2017-11-12t09:00:05.000z
14  2017-11-13t11:59:43.000z
15  2017-11-12t16:09:44.000z
16  2017-11-13t14:03:32.000z

                                                 tags   views  likes  \
5                                              [none]   32709   3093
13  liebscher|"bracht"|"faszien"|"lnb"|"schmerzthe...  109571   4357
14  planetkanax|"planet"|"kanax"|"planet kanax"|"a...   99988   6397
15        welt|"natur"|"umwelt"|"klima"|"klimawandel"   37877   1839
16  fußball challenge|"brotatos"|"fußball"|"footba...  111328  10692

    dislikes  comment_count                                  thumbnail_link  \
5        296             63  https://i.ytimg.com/vi/xapgfgwqtg4/default.jpg
13       303            357  https://i.ytimg.com/vi/mmmpprcmjea/default.jpg
14       298            429  https://i.ytimg.com/vi/3u51cviqulm/default.jpg
15       327            170  https://i.ytimg.com/vi/okyuthvgmhc/default.jpg
16       115            548  https://i.ytimg.com/vi/spwqqdcw4ti/default.jpg

    comments_disabled  ratings_disabled  video_error_or_removed  \
5               False             False                   False
13              False             False                   False
14              False             False                   False
15              False             False                   False
16              False             False                   False

                                          description
5   wir haben meinungsstudie.de (► http://bit.ly/2...
13  weitere infos zu diesem thema findest du hier:...
14  video mit bodyformus: https://youtu.be/eim7rme...
15  über die zukunft nachzudenken macht spaß, oder...
16  die rundlauf fußball challenge! jeder kennt da...